name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          make install
        shell: bash

      - name: Lint and Test
        run: |
          make check
        shell: bash
        if: runner.os == 'Linux'

      - name: Install dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          make install
        shell: pwsh
        if: runner.os == 'Windows'

      - name: Lint and Test (Windows)
        run: |
          make check
        shell: pwsh
        if: runner.os == 'Windows'
